### ISSUE TITLE
Change "" to '' for compatibility with linux

### ISSUE THREAD

**Issue by paolomassa** [i4Ds/STIX-GSW#213] opened 2024-06-05 16:08 UTC
There are some places in the code in which strings are defined within "" (see, e.g., [here](https://github.com/i4Ds/STIX-GSW/blob/bb8acc8accc2ec59a9cbd6e277d4098856c34a2d/stix/idl/demo/stx_imaging_demo.pro#L30C16-L30C28) and [](https://github.com/i4Ds/STIX-GSW/blob/bb8acc8accc2ec59a9cbd6e277d4098856c34a2d/stix/idl/demo/stx_imaging_demo.pro#L34)). This is incompatible with linux distributions. It should be changed to ' ' in the entire software.

**Comment by samaloney** [comment] 2024-10-15 12:59
@paolomassa has any progress been made on this? Are you sure the issue is the `'`s or the encoding of the source files?

**Comment by paolomassa** [comment] 2024-10-15 13:20
We still need to implement the modifications, I'll do that soon. For what I know it should be just a problem of changing " with ' , nothing more.

**Comment by samaloney** [comment] 2024-10-15 13:27
Ok I guess I just don't understand the problem "linux" doesn't have an issue with `"` or `'` so it must be IDL on linux and even then I don't really understand. I have had encoding issues before ascii / utf-8 / utf-16 etc

**Comment by paolomassa** [comment] 2024-10-15 13:40
For what I understood, the problem is that the IDL installation on linux has troubles sometimes when strings are defined within `"`. If I remember correctly, @PaipaPsyche reported this issue to me.

@PaipaPsyche could you please tell us more if it was you who found this issue? Thanks!

**Comment by PaipaPsyche** [comment] 2024-10-15 14:16
I'm running SSW on an Ubuntu distribution. For some reason I always have an error when running the demo because of these "" strings (the subroutines cannot recognize the specified date/UID ). The error disappears when replacing the " for ' in the scripts.

**Comment by PaipaPsyche** [comment] 2024-10-15 15:36
it's ASCII

**Comment by samaloney** [comment] 2024-11-25 10:15
Closed in #226

**Closed by samaloney** 2024-11-25 10:15 UTC
Labels: bug, reviewed 2024-10
